const actionTypes = {
    FETCH_PATIENTS_START: "FETCH_PATIENTS_START",
    FETCH_PATIENTS_SUCCESS: " FETCH_PATIENTS_SUCCESS",
    FETCH_PATIENTS_FAIL: "FAIL",
    ADD_PATIENT: "ADD_PATIENT",
    DELETE_PATIENT: "DELETE_PATIENT",
    EDIT_PATIENT: "EDIT_PATIENT",
    FETCH_APPOINTMENTS_START: "FETCH_APPOINTMENTS_START",
    FETCH_APPOINTMENTS_SUCCESS: " FETCH_APPOINTMENTS_SUCCESS",
    FETCH_APPOINTMENTS_FAIL: "FAIL",
    ADD_APPOINTMENT: "ADD_APPOINTMENT",
    DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
    EDIT_APPOINTMENT: "EDIT_APPOINTMENT",
    FETCH_OPERATIONS_START: "FETCH_OPERATIONS_START",
    FETCH_OPERATIONS_SUCCESS: " FETCH_OPERATIONS_SUCCESS",
    FETCH_OPERATIONS_FAIL: "FAIL",
    ADD_OPERATION: "ADD_OPERATION",
    DELETE_OPERATION: "DELETE_OPERATION",
    EDIT_OPERATION: "EDIT_OPERATION"
}
export default actionTypes;